### ISSUE TITLE
Android support

### ISSUE THREAD

**Issue by Frostik007** [Falcosc/locus-addon-tasker#36]
I have Samsung Galaxy S21 (SM-G991B/DS) with Android 14 and in Play store it says the phone is not compatible with the app. What could be the problem?

**Comment by Falcosc** [comment]
use this link to join or leave the beta programm
https://play.google.com/apps/testing/falcosc.locus.addon.tasker

And let me know how it goes. I did rollback to 2021 since it had some issues which are solved now. But now I holding back the new version until some experience from you.

**Comment by Frostik007** [comment]
I did what you said, but the app is still not available for installation on
my phone.

**Comment by Falcosc** [comment]
Can you check if join to test did work?
Do you have a 2nd phone to check if the installed version is 1.7.1-Snaphot instead of
1.6.0?

Otherwise, you can sideload it and tell me how well it works to help me deciding when we could actually publish 1.7.1 to production.

[locusTasker1.7.1-82.apk.zip](https://github.com/user-attachments/files/18717470/locusTasker1.7.1-82.apk.zip)

**Comment by Frostik007** [comment]
Hello, joining to Beta shown me just info that I am in the beta test, but
still shown the phone is not compatible.

Installation from apk went correctly, I see the plugin in Tasker.

However, it looks like the broadcasts are not working correctly. I went
through developer options and disabled isolated space (2nd last), but
nothing changed. Even starting Locus as a service made no difference.

I attach the 3 types of tasks I tried so far.
In the past worked the "Start Locus Recording".
After some Android updates I noticed the original task does not work, so I
played with newly introduced messages, but I didn't make it working.
The last one is "Start Locus Recording Plugin", but it does not work either.

I'm using Locus Classic 3.70.15. Should I try with the new Locus 4?

Dne so 8. 2. 2025 8:57 uživatel Falcosc ***@***.***> napsal:

**Comment by Falcosc** [comment]
You need to use Github UI, attachments are not handled over email.

Did you test:
Request Sensors and Stats?
Get Locus Info?

Or did you only test Execute action tasks?

Do you have ADB shell access to do some tests manually if we need some iterations to find the issue instead of building 5 different test versions?

**Comment by Falcosc** [comment]
ADB Shell is useful for action Tasks tests

I did not need to setup anything to get them working:

```
\Sdk\platform-tools\adb.exe shell
ps | grep locus
```

and then use the output package name for the test command:

```
am broadcast -a com.asamm.locus.ACTION_TASK --es tasks '{ map_zoom: { action: "+" } }' menion.android.locus
```

**Comment by Falcosc** [comment]
@Frostik007 Please focus on Map Zoom for testing because at least on my emulator I have trouble with Start Track Recording on Locus 4.28.0 but don't know if this is expected behaivor or not https://github.com/asamm/locus-api/issues/59

**Comment by Falcosc** [comment]
But does Map Zoom work always to prove that Plugin to Locus connection works?
What about Request Sensors and Stats? Does it work as well as on my side?

**Comment by Falcosc** [comment]
It is now on production, let me know if google decides to mark your device as eligible. If not let me know to get some details from Google about this.

**Comment by Frostik007** [comment]
Yes, it is there as a version to update.

I will check other plugin functions, but it seems to be working well.

Thank you for prompt support and good luck in further projects :)
